print("=== Анализ последовательности ДНК ===\n")
dna=input("Введите последовательность ДНК: ")
print(" ")
dna_upper=dna.upper()
x=len(dna)
print(f"Последовательность в верхнем регистре: {dna_upper}\n")
print("Подсчёт нуклеотидов:")
print(f"A: {dna_upper.count("A")}\t{int(dna_upper.count("A"))/int(x):.2f}")
print(f"T: {dna_upper.count("T")}\t{int(dna_upper.count("T"))/int(x):.2f}")
print(f"G: {dna_upper.count("G")}\t{int(dna_upper.count("G"))/int(x):.2f}")
print(f"C: {dna_upper.count("C")}\t{int(dna_upper.count("C"))/int(x):.2f}\n")
print(f"Общее число нуклеотидов: {x}")
